kind: pipeline
name: default

steps:
- name: test
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  commands:
  - dotnet restore
  - dotnet test
  volumes:
  - name: app
    path: /app
- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  commands:
  - dotnet publish ./SimpleAPI -c Release --self-contained true -r linux-musl-x64 -o ./build
  - ls ./SimpleAPI/build
  volumes:
  - name: app
    path: /app
- name: deploy
  image: docker
  privileged: true
  commands:
  - ls
  - docker ps
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host: 
    path: /var/run/docker.sock
- name: app
  temp: {}
