kind: pipeline
name: default

steps:
- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  commands:
  - dotnet restore
  - dotnet publish ./PayrollAPI -c Debug --self-contained true -r linux-musl-x64 -o ./builds/PayrollAPI
  - ls ./builds/PayrollAPI
  volumes:
  - name: app
    path: /app
