kind: pipeline
name: default

steps:
- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  commands:
  - dotnet restore
  - dotnet publish -c Release --self-contained true -r linux-musl-x64 -o ./builds/TestRepo
  - ls ./builds/TestRepo
  volumes:
  - name: app
    path: /app
